services:
  hacofpt-fe-admin:
    container_name: hacofpt-fe-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_REDIRECT_URI=${NEXT_PUBLIC_REDIRECT_URI}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    volumes:
      - ./public:/app/public
    networks:
      - hacofpt-network

networks:
  hacofpt-network:
    driver: bridge
